# Generated by Django 2.0.2 on 2019-04-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('rowid', models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('pubmedid', models.IntegerField(blank=True, db_column='PUBMEDID', null=True)),
                ('journal', models.TextField(blank=True, db_column='JOURNAL', null=True)),
                ('link', models.TextField(blank=True, db_column='LINK', null=True)),
                ('study', models.TextField(blank=True, db_column='STUDY', null=True)),
                ('date', models.TextField(blank=True, db_column='DATE', null=True)),
            ],
            options={
                'db_table': 'ARTICLE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Snp',
            fields=[
                ('rowid', models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('chr_id', models.IntegerField(blank=True, db_column='CHR_ID', null=True)),
                ('chr_pos', models.TextField(blank=True, db_column='CHR_POS', null=True)),
                ('rsid_current', models.IntegerField(blank=True, db_column='RSID_CURRENT', null=True)),
            ],
            options={
                'db_table': 'SNP',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Snp2Phenotype2Ref',
            fields=[
                ('rowid', models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('snp_id', models.IntegerField(blank=True, db_column='SNP_ID', null=True)),
                ('disease_trait_id', models.IntegerField(blank=True, db_column='DISEASE_TRAIT_ID', null=True)),
                ('reference_id', models.IntegerField(blank=True, db_column='REFERENCE_ID', null=True)),
                ('p_value', models.IntegerField(blank=True, db_column='P_VALUE', null=True)),
                ('pvalue_mlog', models.TextField(blank=True, db_column='PVALUE_MLOG', null=True)),
            ],
            options={
                'db_table': 'SNP2PHENOTYPE2REF',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TableDisease',
            fields=[
                ('rowid', models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('disease_trait', models.TextField(blank=True, db_column='DISEASE_TRAIT', null=True)),
            ],
            options={
                'db_table': 'TABLE_DISEASE',
                'managed': False,
            },
        ),
    ]
